name: file_store
description: A web server built using the shelf package for DB class.
authors:
  - Ali Ghanbari

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0